-- ============================================================
-- Coach Merche App — Clases de demo (LEGACY / OPCIONAL)
--
-- ⚠️  Las clases recurrentes ya se generan automáticamente con la
--     migración 20260809121100_recurring_classes.sql mediante la
--     función public.ensure_recurring_classes().
--
-- Horario fijo (Europe/Madrid):
--   · Martes  19:00 → Full Body
--   · Jueves  19:00 → EMOM Táctico
--
-- Para extender o regenerar la ventana futura (p. ej. 12 semanas):
--
--   select public.ensure_recurring_classes(12);
--
-- Ejecutar en el SQL Editor de Supabase (rol service_role o postgres).
-- La función es idempotente: no crea duplicados.
--
-- Este script antiguo insertaba clases de ejemplo con fechas y horas
-- arbitrarias. Conservado solo como referencia histórica; NO usar en
-- producción salvo pruebas puntuales en entornos vacíos.
-- ============================================================

-- Referencia del comportamiento automático (no ejecutar en prod):
-- select public.ensure_recurring_classes(12);
